#server:
#  port: 81

#demo4
#设置启用环境
#spring:
#  profiles:
#    active: dev
---
#开发环境
#spring:
#  profiles: dev  过时写法，但没区别

#spring:
#  config:
#    activate:
#      on-profile: dev
#server:
#  port: 80
#---
##生产环境
#spring:
#  profiles: pro
#server:
#  port: 81
#---
##测试环境
#spring:
#  profiles: test
#server:
#  port: 82


#demo5
#
#spring:
#  profiles:
#    active: ${profile.active}
#---
#
#spring:
#  config:
#    activate:
#      on-profile: dev
#server:
#  port: 80
#---
##生产环境
#spring:
#  profiles: pro
#server:
#  port: 81
#---
##测试环境
#spring:
#  profiles: test
#server:
#  port: 82
#---


#demo6
server:
  port: 80

