#server:
#  port: 82


#logging:
#  level:
#    root: info


#likes:
#  - swimming
#  - sing


#demo3
#lesson: SpringBoot
#
#server:
#  port: 80
#
#enterprise:
#  name: itcast
#  age: 16
#  tel: 4006184000
#  subject:
#    - Java
#    - 前端
#    - 大数据
#


